### ISSUE TITLE
No rewards for arriving/farming a planet

### ISSUE THREAD

**Issue by Mustang12345** [onikamigames/starshipgame#183]
It happened now the 3rd time. I choose a planet for a mission to launch - after the timer went to 0sec there is option appearing for farming, claiming or whatever should appear. I get 0 kyanite and had to pay 190 kyanite.
Acc Mustang12345

**Comment by Evelloncrypto** [comment]
Same happens when I leave my ships unattended an extended period of time. Could this be due to planet pools refreshing while a starship is "sitting" on it? Can't exactly duplicate the error as it just sends the ships back to "select mission" starting from choosing where to send the ships to. Have had multiple reports of this.

WAX account name: evellontest4
MM address: 0x44fbB8b967773E97192d2c56C17fF8447385A6fd
Browser: Chrome

**Comment by Mazh56** [comment]
So it's happen 2 times for me, I send a ship on a chip planet (1 parsec) and after the time travel my ship just return into the space station without any reward, i can just send it again to an another planet (I tried a second time to see if that an error and I get the same issue) 

Here is my WAX testnet account name : **_mazyhmazyh21_**
My MM (BSC) address : **_0xB61D11Ba1fF6af0c15DD54BF1C2aaAEE90a1c5c5_**
I'm using **_Brave_** to play to the alpha
and the last error occurrence happen around **_11:30PM_** (UTC+1) 
Thanks for taking time to read this! 💯

**Comment by Evelloncrypto** [comment]
@onikamigames pinging for importance. Thanks for your help!

See also https://github.com/onikamigames/starshipgame/issues/165

**Comment by Evelloncrypto** [comment]
**Do not send your ships to planet ID 0**

It's a metallic planet in the top quadrant, first sector, first system. Just don't do it!
