### ISSUE TITLE
Iman stuck with space staion

### ISSUE THREAD

**Issue by Amerchiro1314** [onikamigames/starshipgame#458]
Im good. I do not know how to delete.

**Comment by kapitanbuto** [comment]
i'm still stuck on space station selection. i'm already un-synced by the devs but still the same. i also tried the wax.bloks.io, but appears "transaction net usage is too high: 128 > 0". i have 10 dollar worth of starship token and have 11.85 waxp staked on my CPU. i'm using microsoft edge since i can't use chrome because i have another mm wallet signed in.  what do i need to work for me be able to play this game, it's already days since i can't play this game. hope you can help me.

**Comment by buraxz** [comment]
I'm having a space station connection problem. I tried all the solutions but it doesn't work. I have 31 starships in my matemask account, but this is the error I get when I try via the blocks link.
Error
assertion failure with message: You don't have enought Starship in your wallet
